### ISSUE TITLE
Logstash error on opsgenie output plugin

### ISSUE THREAD

**Issue by danielmotaleite** [opsgenie/logstash-output-opsgenie#5]
Latest plugin version, running in logstash 5.2.1 give this error:

```
[2017-02-28T17:58:06,905][FATAL][logstash.runner          ] An unexpected error occurred! 
{:error=>#<NoMethodError: Direct event field references (i.e. event['field']) have been disabled in favor of using event get and set methods (e.g. event.get('field')). 
 Please consult the Logstash 5.0 breaking changes documentation for more details.>,
 :backtrace=>["/usr/share/logstash/logstash-core-event-java/lib/logstash/event.rb:45:in `method_missing'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-opsgenie-2.0.5/lib/logstash/outputs/opsgenie.rb:177:in `receive'", 
  "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'",
  "org/jruby/RubyArray.java:1613:in `each'",
  "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'",
  "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'",
  "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:43:in `multi_receive'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:336:in `output_batch'",
  "org/jruby/RubyHash.java:1342:in `each'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:335:in `output_batch'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:293:in `worker_loop'",
  "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:263:in `start_workers'"]}

```

thanks

**Comment by danielmotaleite** [comment]
a simple  regexp replace to `/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-opsgenie-2.0.5/lib/logstash/outputs/opsgenie.rb` like this fix the problem:

`s/ event\[([^]]*)\]/ event.get(\1)/g`

**Comment by davidban77** [comment]
Thanks! I was facing the same issue and this fixed it

**Comment by danielmotaleite** [comment]
@halitokumus This was closed, but no new commit show up ... was it a accidental close?

**Comment by halitokumus** [comment]
Yes, sorry, I mistook the issue for resolved.
However, I just accepted a merge request and published a new gem, it should apply the fix. Can you check it out?

**Comment by danielmotaleite** [comment]
just updated the plugin and created a test event and it worked fine, so this is fix, can be closed.

Thanks for the help!
